### ISSUE TITLE
Increase maximum edge length.

### ISSUE THREAD

**Issue by sjackso** [lcbb/athena#13]
@hmjeon says: For the Athena, current version has maximum edge length as 126-bp, could you also increase it up to 210-bp? We used 210-bp DNA origami in the paper.

Question: is this new limit appropriate for all 4 of the tools?

**Comment by zoombya** [comment]
Sorry, I'm trying to run this version on macOS Sonoma Version 14.2.1 (23C71)
While contrary to other versions this release is opening the app, no gui appears, and the program appears to be stuck 
Command line output is:
`(base) ➜  MacOS ./Athena 
Athena version is 0.4.7.dev2+gb01e6a0
Athena's output directory will be /var/folders/8k/hb5nx1vx7zg6srky_7h0dxv00000gn/T/Athena5ls_jy1r
qt.qpa.fonts: Populating font family aliases took 248 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. ` 

Thx in advance for your help.
